<html>
<head>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
    Test View
</title>
<body>
<form action="#" method="post" id="userFormData">
    <label>First Name</label><input type="text" name="firstName"><br>
    <label>Last Name</label><input type="text" name="lastName"><br>
    <label>User Name</label><input type="text" name="userName"><br>
    <label>Email Address</label><input type="text" name="emailAddress"><br>
    <label>Password</label><input type="password" name="password"><br>
    <input type="button" name="submit" value="submit" id="userform">
    <input type="button" name="submit" value="userview" id="editform">

    <a href="<?=$this->url(array('controller'=>'index','action'=>'edit/2'))?>">Edit User Info</a>
</form>
<script type="text/javascript">
        $("#userform").click(function(){
          $.ajax({
              type: "POST",
             // url:'test',
              url:'http://localhost/zend_webservice/public/index.php/user/adduser',
              //data:$('#userFormData').serialize(),
              success:function(data){
                  console.log(data);
              }
          });
        });
    $('#editform').click(function(){
        $.ajax({
            type:"GET",
            url:"edit?id="+2,
            dataType:'json',
        success:function(data){
            console.log(data);
        }
        });
    });
</script>
</body>
</html>