<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
    Add User
</title>
<body>
<form action="#" method="post" id="sendphone">
    <label>Phone Number</label><input type="text" name="phoneNumber"><br>
    <label>Email Address</label><input type="text" name="emailAddress"><br>
    <input type="submit" name="submit" value="Add User"/>
    </form>
<script type="text/javascript">
    $('#adduserphone').click(function(){
        $.ajax({
            type:"POST",
            url:"http://weexcel.biz/zend_webservice/public/index.php/user/adduser",
            data:$('#sendphone').serialize(),
            dataType:"json",
            success:function(response){
                console.log(response);
            }
        });
    });
</script>
</body>
</html>