<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
    Update Password
</title>
<body>
<form action="#" method="post" id="update">
    <label>Store Id </label>: <input type="text" name="store_id"><br>
    <label>Password </label>: <input type="password" name="password" ><br>
    <input type="submit" name="submit" value="submit"/>

    </form>
</body>
</html>
