<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
   Update fileds
</title>
<body>
<form action="#" method="post" id="updatestoreinfo">
    <label>Store Id</label>:<input type="text" name="store_id" value="2" readonly="true"><br>
    <label>store name</label><input type="text" name="storename" value=""/><br>
    <label>store address</label><input type="text" name="storeaddresss" value=""/><br>

    <input type="submit" name="submit" value="submit">
</form>