<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
    Add User
</title>
<body>
<form action="#" method="post" id="updatestoreinfo">
    <label>Store Id</label>:<input type="text" name="store_id"><br>
    <label>StoreName </label>:<input type="text" name="storeName"><br>
    <label>Address</label>:<input type="text" name="address" ><br>
    <label>Address Details</label>:<input type="text" name="addressDetails"><br>
  <label>PhoneNumber</label>: <input type="text" name="phoneNumber"><br>

<input type="submit" name="submit" value="submit">
    </form>
