<html>
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<title>
   Login User
</title>
<body>
<form action="#" method="post" id="updatestoreinfo">
    <label>Phone Number </label>:<input type="text" name="phoneNumber"><br>
    <label>Password </label>:<input type="password" name="password" >
    <input type="submit" name="submit" value="submit">
</form>